"""empty message

Revision ID: 2e259d89fbb2
Revises: b2fcf6ddbc63
Create Date: 2023-02-18 10:26:42.185272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e259d89fbb2'
down_revision = 'b2fcf6ddbc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_content', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('flag_content')

    # ### end Alembic commands ###
