"""Added users to user challenge

Revision ID: 4b9c53e24795
Revises: 8643f8b7ad8d
Create Date: 2022-11-04 10:57:51.235171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9c53e24795'
down_revision = '8643f8b7ad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_challenges', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_challenges', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_challenges', type_='foreignkey')
    op.drop_column('user_challenges', 'user_id')
    # ### end Alembic commands ###
