"""Added challenge table

Revision ID: 666f8805bf52
Revises: a1da2fdc2d3b
Create Date: 2022-11-04 09:33:32.323167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666f8805bf52'
down_revision = 'a1da2fdc2d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    # ### end Alembic commands ###
