"""Added hints

Revision ID: 7cb6d00787f7
Revises: 750b6589ead9
Create Date: 2022-11-04 10:00:59.238807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb6d00787f7'
down_revision = '750b6589ead9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_hint')
    # ### end Alembic commands ###
