"""Updated hints

Revision ID: a448e3ff842e
Revises: 666f8805bf52
Create Date: 2022-11-04 09:52:18.500261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a448e3ff842e'
down_revision = '666f8805bf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('hints', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'hints')
    # ### end Alembic commands ###
