"""empty message

Revision ID: b2fcf6ddbc63
Revises: bc48b5016ed6
Create Date: 2022-11-21 12:41:29.518457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fcf6ddbc63'
down_revision = 'bc48b5016ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_allowed', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_started', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.drop_column('time_started')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('time_allowed')

    # ### end Alembic commands ###
