"""empty message

Revision ID: b75f617b0217
Revises: 2e259d89fbb2
Create Date: 2023-02-18 10:28:27.783836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75f617b0217'
down_revision = '2e259d89fbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_completions_challenge_id_challenges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_challenge_completions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_completions'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_allowed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flag_content', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_started', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.drop_column('time_started')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('flag_content')
        batch_op.drop_column('time_allowed')

    op.drop_table('challenge_completions')
    # ### end Alembic commands ###
