"""empty message

Revision ID: e125759581b2
Revises: b75f617b0217
Create Date: 2023-03-08 07:38:25.589993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e125759581b2'
down_revision = 'b75f617b0217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###
