"""Added challenge hints

Revision ID: e37503d60fa3
Revises: 7cb6d00787f7
Create Date: 2022-11-04 10:02:35.312985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37503d60fa3'
down_revision = '7cb6d00787f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('challenge_hint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_hint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hint', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('challenge_hints')
    # ### end Alembic commands ###
